# 9 WorkFlow Analista Jr

### 9.1 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
<br>El Analista Jr corre sus scripts en la virtual manchine **desktop-jr** que tiene estas características


*   Normal, paga tarifa completa, nunca es apagada por Google
*   reside en el datacenter de Toronto, Canada
*   64 GB de memoria RAM
*   8 vCPU


En Analista Jr **no** puede utilizar Google Colab porque los 12 GB de dichas maquinas virtuales no son suficientes para el tamaño del dataset que está utilizando.

## 9.3  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Tue Sep 15 01:24:36 2026"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671174 35.9 1479534    79.1 1479534  79.1
Vcells 1242566  9.5 8388608    64.0 1978697  15.1

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:base’:

    %notin%


Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
semillas <- c(146023, 419921, 453601, 906313, 994481, 100003, 200003, 300007, 400009, 500009)
exp_base <- 5000  

for(i in 1:length(semillas)) {
  
  PARAM <- list()  
  PARAM$semilla_primigenia <- semillas[i]
  PARAM$experimento        <- exp_base + i
  PARAM$dataset            <- "analistajr_competencia_2026.csv.gz"
  
}

#### Carpeta del Experimento

In [5]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("WF", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

### 9.3.1   Preprocesamiento del dataset

#### 9.3.1.1  DT incorporar dataset

In [6]:
# lectura del dataset
dataset <- fread(paste0("/content/datasets/", PARAM$dataset))

#### 9.3.1.2  CA  Catastrophe Analysis
Se intentan reparar las variables que para un mes están con todos los valores en cero.

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

In [7]:
if( !require("mice")) install.packages("mice", repos = "http://cran.us.r-project.org")
require("mice")

Loading required package: mice


Attaching package: ‘mice’


The following object is masked from ‘package:stats’:

    filter


The following objects are masked from ‘package:base’:

    cbind, rbind

In [8]:
# Escrito por alumnos de  Universidad Austral  Rosario

Corregir_MICE <- function(pcampo, pmeses) {

  meth <- rep("", ncol(dataset))
  names(meth) <- colnames(dataset)
  meth[names(meth) == pcampo] <- "sample"

  # llamada a mice  !
  imputacion <- mice(dataset,
    method = meth,
    maxit = 5,
    m = 1,
    seed = 7)

  tbl <- mice::complete(dataset)

  dataset[, paste0(pcampo) := ifelse(foto_mes %in% pmeses, tbl[, get(pcampo)], get(pcampo))]

}

In [9]:
Corregir_interpolar <- function(pcampo, pmeses) {

  tbl <- dataset[, list(
    "v1" = shift(get(pcampo), 1, type = "lag"),
    "v2" = shift(get(pcampo), 1, type = "lead")
  ),
  by = eval(envg$PARAM$dataset_metadata$entity_id)
  ]

  tbl[, paste0(envg$PARAM$dataset_metadata$entity_id) := NULL]
  tbl[, promedio := rowMeans(tbl, na.rm = TRUE)]

  dataset[
    ,
    paste0(pcampo) := ifelse(!(foto_mes %in% pmeses),
      get(pcampo),
      tbl$promedio
    )
  ]
}

In [10]:
AsignarNA_campomeses <- function(pcampo, pmeses) {

  if( pcampo %in% colnames( dataset ) ) {

    dataset[ foto_mes %in% pmeses, paste0(pcampo) := NA ]
  }
}

In [11]:

Corregir_atributo <- function(pcampo, pmeses, pmetodo)
{
  # si el campo no existe en el dataset, Afuera !
  if( !(pcampo %in% colnames( dataset )) )
    return( 1 )

  # llamo a la funcion especializada que corresponde
  switch( pmetodo,
    "MachineLearning"     = AsignarNA_campomeses(pcampo, pmeses),
    "EstadisticaClasica"  = Corregir_interpolar(pcampo, pmeses),
    "MICE"                = Corregir_MICE(pcampo, pmeses),
  )

  return( 0 )
}

In [12]:

Corregir_Rotas <- function(dataset, pmetodo) {
  gc(verbose= FALSE)
  cat( "inicio Corregir_Rotas()\n")
  # acomodo los errores del dataset

  Corregir_atributo("active_quarter", c(202006), pmetodo) # 1
  Corregir_atributo("internet", c(202006), pmetodo) # 2

  Corregir_atributo("mrentabilidad", c(201905, 201910, 202006), pmetodo) # 3
  Corregir_atributo("mrentabilidad_annual", c(201905, 201910, 202006), pmetodo) # 4

  Corregir_atributo("mcomisiones", c(201905, 201910, 202006), pmetodo) # 5

  Corregir_atributo("mactivos_margen", c(201905, 201910, 202006), pmetodo) # 6
  Corregir_atributo("mpasivos_margen", c(201905, 201910, 202006), pmetodo) # 7

  Corregir_atributo("mcuentas_saldo", c(202006), pmetodo) # 8

  Corregir_atributo("ctarjeta_debito_transacciones", c(202006), pmetodo) # 9

  Corregir_atributo("mautoservicio", c(202006), pmetodo) # 10

  Corregir_atributo("ctarjeta_visa_transacciones", c(202006), pmetodo) # 11
  Corregir_atributo("mtarjeta_visa_consumo", c(202006), pmetodo) # 12

  Corregir_atributo("ctarjeta_master_transacciones", c(202006), pmetodo) # 13
  Corregir_atributo("mtarjeta_master_consumo", c(202006), pmetodo) # 14

  Corregir_atributo("ctarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 15
  Corregir_atributo("mttarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 16

  Corregir_atributo("ccajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 17

  Corregir_atributo("mcajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 18

  Corregir_atributo("ctarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 19

  Corregir_atributo("mtarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 20

  Corregir_atributo("ctarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 21

  Corregir_atributo("mtarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 22

  Corregir_atributo("ccomisiones_otras", c(201905, 201910, 202006), pmetodo) # 23
  Corregir_atributo("mcomisiones_otras", c(201905, 201910, 202006), pmetodo) # 24

  Corregir_atributo("cextraccion_autoservicio", c(202006), pmetodo) # 25
  Corregir_atributo("mextraccion_autoservicio", c(202006), pmetodo) # 26

  Corregir_atributo("ccheques_depositados", c(202006), pmetodo) # 27
  Corregir_atributo("mcheques_depositados", c(202006), pmetodo) # 28
  Corregir_atributo("ccheques_emitidos", c(202006), pmetodo) # 29
  Corregir_atributo("mcheques_emitidos", c(202006), pmetodo) # 30
  Corregir_atributo("ccheques_depositados_rechazados", c(202006), pmetodo) # 31
  Corregir_atributo("mcheques_depositados_rechazados", c(202006), pmetodo) # 32
  Corregir_atributo("ccheques_emitidos_rechazados", c(202006), pmetodo) # 33
  Corregir_atributo("mcheques_emitidos_rechazados", c(202006), pmetodo) # 34

  Corregir_atributo("tcallcenter", c(202006), pmetodo) # 35
  Corregir_atributo("ccallcenter_transacciones", c(202006), pmetodo) # 36

  Corregir_atributo("thomebanking", c(202006), pmetodo) # 37
  Corregir_atributo("chomebanking_transacciones", c(201910, 202006), pmetodo) # 38

  Corregir_atributo("ccajas_transacciones", c(202006), pmetodo) # 39
  Corregir_atributo("ccajas_consultas", c(202006), pmetodo) # 40

  Corregir_atributo("ccajas_depositos", c(202006, 202105), pmetodo) # 41

  Corregir_atributo("ccajas_extracciones", c(202006), pmetodo) # 41
  Corregir_atributo("ccajas_otras", c(202006), pmetodo) # 43

  Corregir_atributo("catm_trx", c(202006), pmetodo) # 44
  Corregir_atributo("matm", c(202006), pmetodo) # 45
  Corregir_atributo("catm_trx_other", c(202006), pmetodo) # 46
  Corregir_atributo("matm_other", c(202006), pmetodo) # 47

  cat( "fin Corregir_rotas()\n")
}

In [13]:
# resuelvo el Catastrophe Analysis

setorder( dataset, numero_de_cliente, foto_mes )

PARAM$CA$metodo= "MachineLearning"

if( PARAM$CA$metodo %in% c("MachineLearning", "EstadisticaClasica", "MICE") )
  Corregir_Rotas(dataset, PARAM$CA$metodo)

inicio Corregir_Rotas()
fin Corregir_rotas()

#### 9.3.1.3  DR  Data Drifting
Se intenta corregir el data drifting, ajustando por algunos indices financieros

In [14]:
# meses que me interesan para el ajuste de variables monetarias
vfoto_mes <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107, 202108, 202109
)

In [15]:
# los valores que siguen fueron calculados por alumnos

# momento 1.0  31-dic-2020 a las 23:59
vIPC <- c(
  1.9903030878, 1.9174403544, 1.8296186587,
  1.7728862972, 1.7212488323, 1.6776304408,
  1.6431248196, 1.5814483345, 1.4947526791,
  1.4484037589, 1.3913580777, 1.3404220402,
  1.3154288912, 1.2921698342, 1.2472681797,
  1.2300475145, 1.2118694724, 1.1881073259,
  1.1693969743, 1.1375456949, 1.1065619600,
  1.0681100000, 1.0370000000, 1.0000000000,
  0.9680542110, 0.9344152616, 0.8882274350,
  0.8532444140, 0.8251880213, 0.8003763543,
  0.7763107219, 0.7566381305, 0.7289384687
)

vdolar_blue <- c(
   39.045455,  38.402500,  41.639474,
   44.274737,  46.095455,  45.063333,
   43.983333,  54.842857,  61.059524,
   65.545455,  66.750000,  72.368421,
   77.477273,  78.191667,  82.434211,
  101.087500, 126.236842, 125.857143,
  130.782609, 133.400000, 137.954545,
  170.619048, 160.400000, 153.052632,
  157.900000, 149.380952, 143.615385,
  146.250000, 153.550000, 162.000000,
  178.478261, 180.878788, 184.357143
)

vdolar_oficial <- c(
   38.430000,  39.428000,  42.542105,
   44.354211,  46.088636,  44.955000,
   43.751429,  54.650476,  58.790000,
   61.403182,  63.012632,  63.011579,
   62.983636,  63.580556,  65.200000,
   67.872000,  70.047895,  72.520952,
   75.324286,  77.488500,  79.430909,
   83.134762,  85.484737,  88.181667,
   91.474000,  93.997778,  96.635909,
   98.526000,  99.613158, 100.619048,
  101.619048, 102.569048, 103.781818
)

vUVA <- c(
  2.001408838932958,  1.950325472789153,  1.89323032351521,
  1.8247220405493787, 1.746027787673673,  1.6871348409529485,
  1.6361678865622313, 1.5927529755859773, 1.5549162794128493,
  1.4949100586391746, 1.4197729500774545, 1.3678188186372326,
  1.3136508617223726, 1.2690535173062818, 1.2381595983200178,
  1.211656735577568,  1.1770808941405335, 1.1570338657445522,
  1.1388769475653255, 1.1156993751209352, 1.093638313080772,
  1.0657171590878205, 1.0362173587708712, 1.0,
  0.9669867858358365, 0.9323750098728378, 0.8958202912590305,
  0.8631993702994263, 0.8253893405524657, 0.7928918905364516,
  0.7666323845128089, 0.7428976357662823, 0.721615762047849
)

In [16]:
tb_indices <- as.data.table( list(
  "IPC" = vIPC,
  "dolar_blue" = vdolar_blue,
  "dolar_oficial" = vdolar_oficial,
  "UVA" = vUVA
  )
)

tb_indices[[ 'foto_mes' ]] <- vfoto_mes

tb_indices

   IPC       dolar_blue dolar_oficial UVA       foto_mes
1  1.9903031  39.04545   38.43000     2.0014088 201901
2  1.9174404  38.40250   39.42800     1.9503255 201902
3  1.8296187  41.63947   42.54210     1.8932303 201903
4  1.7728863  44.27474   44.35421     1.8247220 201904
5  1.7212488  46.09546   46.08864     1.7460278 201905
6  1.6776304  45.06333   44.95500     1.6871348 201906
7  1.6431248  43.98333   43.75143     1.6361679 201907
8  1.5814483  54.84286   54.65048     1.5927530 201908
9  1.4947527  61.05952   58.79000     1.5549163 201909
10 1.4484038  65.54546   61.40318     1.4949101 201910
11 1.3913581  66.75000   63.01263     1.4197730 201911
12 1.3404220  72.36842   63.01158     1.3678188 201912
13 1.3154289  77.47727   62.98364     1.3136509 202001
14 1.2921698  78.19167   63.58056     1.2690535 202002
15 1.2472682  82.43421   65.20000     1.2381596 202003
16 1.2300475 101.08750   67.87200     1.2116567 202004
17 1.2118695 126.23684   70.04789     1.1770809 202005
18 1.1881073 125.85714   72.52095     1.1570339 202006
19 1.1693970 130.78261   75.32429     1.1388769 202007
20 1.1375457 133.40000   77.48850     1.1156994 202008
21 1.1065620 137.95454   79.43091     1.0936383 202009
22 1.0681100 170.61905   83.13476     1.0657172 202010
23 1.0370000 160.40000   85.48474     1.0362174 202011
24 1.0000000 153.05263   88.18167     1.0000000 202012
25 0.9680542 157.90000   91.47400     0.9669868 202101
26 0.9344153 149.38095   93.99778     0.9323750 202102
27 0.8882274 143.61539   96.63591     0.8958203 202103
28 0.8532444 146.25000   98.52600     0.8631994 202104
29 0.8251880 153.55000   99.61316     0.8253893 202105
30 0.8003764 162.00000  100.61905     0.7928919 202106
31 0.7763107 178.47826  101.61905     0.7666324 202107
32 0.7566381 180.87879  102.56905     0.7428976 202108
33 0.7289385 184.35714  103.78182     0.7216158 202109

In [17]:
drift_UVA <- function(campos_monetarios) {
  cat( "inicio drift_UVA()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.UVA,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_UVA()\n")
}

In [18]:
drift_dolar_oficial <- function(campos_monetarios) {
  cat( "inicio drift_dolar_oficial()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_oficial,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_oficial()\n")
}

In [19]:
drift_dolar_blue <- function(campos_monetarios) {
  cat( "inicio drift_dolar_blue()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_blue,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_blue()\n")
}

In [20]:
drift_deflacion <- function(campos_monetarios) {
  cat( "inicio drift_deflacion()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.IPC,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_deflacion()\n")
}

In [21]:
drift_rank_simple <- function(campos_drift) {

  cat( "inicio drift_rank_simple()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_rank") :=
      (frank(get(campo), ties.method = "random") - 1) / (.N - 1), by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat( "fin drift_rank_simple()\n")
}

In [22]:
# El cero se transforma en cero
# los positivos se rankean por su lado
# los negativos se rankean por su lado

drift_rank_cero_fijo <- function(campos_drift) {

  cat( "inicio drift_rank_cero_fijo()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[get(campo) == 0, paste0(campo, "_rank") := 0]
    dataset[get(campo) > 0, paste0(campo, "_rank") :=
      frank(get(campo), ties.method = "random") / .N, by = list(foto_mes)]

    dataset[get(campo) < 0, paste0(campo, "_rank") :=
      -frank(-get(campo), ties.method = "random") / .N, by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat("\n")
  cat( "fin drift_rank_cero_fijo()\n")
}

In [23]:
drift_estandarizar <- function(campos_drift) {

  cat( "inicio drift_estandarizar()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_normal") :=
      (get(campo) -mean(campo, na.rm=TRUE)) / sd(get(campo), na.rm=TRUE),
      by = list(foto_mes)]

    dataset[, (campo) := NULL]
  }
  cat( "fin drift_estandarizar()\n")
}

In [24]:
# por como armé los nombres de campos,
#  estos son los campos que expresan variables monetarias
campos_monetarios <- colnames(dataset)
campos_monetarios <- campos_monetarios[campos_monetarios %like%
  "^(m|Visa_m|Master_m|vm_m)"]

campos_monetarios

 [1] "mrentabilidad"                      "mrentabilidad_annual"
 [3] "mcomisiones"                        "mactivos_margen"
 [5] "mpasivos_margen"                    "mcuenta_corriente"
 [7] "mcaja_ahorro"                       "mcuentas_saldo"
 [9] "mtarjeta_visa_consumo"              "mtarjeta_master_consumo"
[11] "mprestamos_personales"              "mpayroll"
[13] "mttarjeta_visa_debitos_automaticos" "mcomisiones_mantenimiento"
[15] "mtransferencias_recibidas"          "Master_mfinanciacion_limite"
[17] "Master_msaldototal"                 "Master_mlimitecompra"
[19] "Master_mconsumototal"               "Master_mpagominimo"
[21] "Visa_mfinanciacion_limite"          "Visa_msaldototal"
[23] "Visa_mlimitecompra"                 "Visa_mconsumototal"
[25] "Visa_mpagominimo"

In [25]:
# ejecuto el Data Drifting
setorder( dataset, numero_de_cliente, foto_mes )


PARAM$DR$metodo <- "deflacion"

switch(PARAM$DR$metodo,
  "ninguno"        = cat("No hay correccion del data drifting"),
  "rank_simple"    = drift_rank_simple(campos_monetarios),
  "rank_cero_fijo" = drift_rank_cero_fijo(campos_monetarios),
  "deflacion"      = drift_deflacion(campos_monetarios),
  "dolar_blue"     = drift_dolarblue(campos_monetarios),
  "dolar_oficial"  = drift_dolaroficial(campos_monetarios),
  "UVA"            = drift_UVA(campos_monetarios),
  "estandarizar"   = drift_estandarizar(campos_monetarios)
)

inicio drift_deflacion()
fin drift_deflacion()

In [26]:
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"

In [27]:
# se intenta corregir el data drifting utilizando algunos indices financieros

#### 9.3.1.3  FE_intra_manual Feature Engineering intra-mes

Agrego campos nuevos dentro del mismo mes, SIN considerar la historia.

In [28]:
# esta funcion atributos presentes existe debido a que las modalidades poseen datasets con distinta cantidad de campos
atributos_presentes <- function( patributos )
{
  atributos <- unique( patributos )
  comun <- intersect( atributos, colnames(dataset) )

  return(  length( atributos ) == length( comun ) )
}

# el mes 1,2, ..12
if( atributos_presentes( c("foto_mes") ))
  dataset[, kmes := foto_mes %% 100]

# variable extraida de una tesis de maestria de Irlanda
if( atributos_presentes( c("mpayroll", "cliente_edad") ))
  dataset[, mpayroll_sobre_edad := mpayroll / cliente_edad]

# ==============================================================================
# EXPERIMENTO 1: Ratios de Dominio Financiero
# ==============================================================================

# Ratios de Tarjetas de Crédito
if (atributos_presentes(c("mtarjeta_visa_consumo", "mtarjeta_master_consumo"))) {
  dataset[, mconsumo_total_tarjetas := mtarjeta_visa_consumo + mtarjeta_master_consumo]
}

if (atributos_presentes(c("ctarjeta_visa_transacciones", "ctarjeta_master_transacciones"))) {
  dataset[, ctrx_total_tarjetas := ctarjeta_visa_transacciones + ctarjeta_master_transacciones]
}

if (atributos_presentes(c("Visa_mpagominimo", "mtarjeta_visa_consumo"))) {
  dataset[, ratio_visa_pagomin_consumo := Visa_mpagominimo / (mtarjeta_visa_consumo + 1)]
}

if (atributos_presentes(c("Master_mpagominimo", "mtarjeta_master_consumo"))) {
  dataset[, ratio_master_pagomin_consumo := Master_mpagominimo / (mtarjeta_master_consumo + 1)]
}

if (atributos_presentes(c("Visa_msaldototal", "Visa_mlimitecompra"))) {
  dataset[, ratio_visa_saldo_limite := Visa_msaldototal / (Visa_mlimitecompra + 1)]
}

if (atributos_presentes(c("Master_msaldototal", "Master_mlimitecompra"))) {
  dataset[, ratio_master_saldo_limite := Master_msaldototal / (Master_mlimitecompra + 1)]
}

# Liquididad y Cuentas
if (atributos_presentes(c("mcaja_ahorro", "mcuenta_corriente"))) {
  dataset[, msaldo_total_liquido := mcaja_ahorro + mcuenta_corriente]
}

if (atributos_presentes(c("mcaja_ahorro", "mcuentas_saldo"))) {
  dataset[, ratio_cajaahorro_cuentas := mcaja_ahorro / (mcuentas_saldo + 1)]
}

if (atributos_presentes(c("mcuenta_corriente", "mcuentas_saldo"))) {
  dataset[, ratio_cuentacorriente_cuentas := mcuenta_corriente / (mcuentas_saldo + 1)]
}

# Interacciones con Payroll e Ingresos
if (atributos_presentes(c("mtarjeta_visa_consumo", "mpayroll"))) {
  dataset[, ratio_consumo_payroll := mtarjeta_visa_consumo / (mpayroll + 1)]
}

if (atributos_presentes(c("mprestamos_personales", "mpayroll"))) {
  dataset[, ratio_prestamos_payroll := mprestamos_personales / (mpayroll + 1)]
}

if (atributos_presentes(c("mrentabilidad", "mpayroll"))) {
  dataset[, mrentabilidad_sobre_payroll := mrentabilidad / (mpayroll + 1)]
}

# Métricas por Producto o Transacción
if (atributos_presentes(c("mcuentas_saldo", "ctrx_quarter"))) {
  dataset[, mtransaccion_promedio_quarter := mcuentas_saldo / (ctrx_quarter + 1)]
}

if (atributos_presentes(c("ctrx_quarter", "cproductos"))) {
  dataset[, ctrx_por_producto := ctrx_quarter / (cproductos + 1)]
}

if (atributos_presentes(c("mrentabilidad", "cproductos"))) {
  dataset[, mrentabilidad_por_producto := mrentabilidad / (cproductos + 1)]
}

# ==============================================================================
# EXPERIMENTO 2: Nuevas variables de dominio (uso, payroll, actividad, liquidez)
# ==============================================================================

# --- Uso y comportamiento de tarjetas ---------------------------------------
if (atributos_presentes(c("mconsumo_total_tarjetas", "ctrx_total_tarjetas"))) {
  dataset[, mconsumo_promedio_trx_tarjeta := mconsumo_total_tarjetas / (ctrx_total_tarjetas + 1)]
}

if (atributos_presentes(c("mtarjeta_visa_consumo", "mtarjeta_master_consumo"))) {
  dataset[, ratio_visa_master_consumo := mtarjeta_visa_consumo / (mtarjeta_master_consumo + 1)]
}

if (atributos_presentes(c("Visa_msaldototal", "Master_msaldototal", "Visa_mlimitecompra", "Master_mlimitecompra"))) {
  dataset[, ratio_uso_limite_total := (Visa_msaldototal + Master_msaldototal) /
            (Visa_mlimitecompra + Master_mlimitecompra + 1)]
}

if (atributos_presentes(c("Visa_Fvencimiento", "foto_mes"))) {
  dataset[, dias_hasta_vto_visa := Visa_Fvencimiento - foto_mes]
}

if (atributos_presentes(c("Master_Fvencimiento", "foto_mes"))) {
  dataset[, dias_hasta_vto_master := Master_Fvencimiento - foto_mes]
}

# --- Ingresos / payroll -------------------------------------------------------
if (atributos_presentes(c("mpayroll_delta1", "mpayroll_delta2"))) {
  dataset[, tendencia_payroll := mpayroll_delta1 - mpayroll_delta2]
}

if (atributos_presentes(c("mpayroll", "mrentabilidad"))) {
  dataset[, ratio_payroll_sobre_rentabilidad := mpayroll / (mrentabilidad + 1)]
}

if (atributos_presentes(c("mpayroll", "mpayroll_lag1"))) {
  dataset[, flag_payroll_caido := as.integer(mpayroll == 0 & mpayroll_lag1 > 0)]
}

# --- Rentabilidad y márgenes ---------------------------------------------------
if (atributos_presentes(c("mactivos_margen", "mpasivos_margen"))) {
  dataset[, ratio_activos_pasivos := mactivos_margen / (mpasivos_margen + 1)]
}

if (atributos_presentes(c("mcomisiones", "mrentabilidad"))) {
  dataset[, ratio_comisiones_sobre_rentabilidad := mcomisiones / (mrentabilidad + 1)]
}

if (atributos_presentes(c("mrentabilidad", "mrentabilidad_lag1", "mrentabilidad_lag2"))) {
  dataset[, volatilidad_rentabilidad := apply(
    cbind(mrentabilidad, mrentabilidad_lag1, mrentabilidad_lag2), 1, sd, na.rm = TRUE)]
}

# --- Antigüedad / ciclo de vida del cliente ------------------------------------
if (atributos_presentes(c("cliente_antiguedad", "cliente_edad"))) {
  dataset[, antiguedad_sobre_edad := cliente_antiguedad / (cliente_edad + 1)]
}

if (atributos_presentes(c("cliente_antiguedad", "cproductos"))) {
  dataset[, antiguedad_por_producto := cliente_antiguedad / (cproductos + 1)]
}

# --- Actividad e inactividad ---------------------------------------------------
if (atributos_presentes(c("ctrx_quarter"))) {
  dataset[, flag_inactivo_trimestre := as.integer(ctrx_quarter == 0)]
}

if (atributos_presentes(c("chomebanking_transacciones", "ctrx_total_tarjetas", "ctrx_quarter"))) {
  dataset[, ratio_homebanking_sobre_actividad := chomebanking_transacciones /
            (ctrx_total_tarjetas + ctrx_quarter + 1)]
}

if (atributos_presentes(c("ctrx_quarter_delta1", "ctrx_quarter_delta2"))) {
  dataset[, tendencia_ctrx := ctrx_quarter_delta1 - ctrx_quarter_delta2]
}

# --- Liquidez y ahorro -----------------------------------------------------------
if (atributos_presentes(c("msaldo_total_liquido", "mpayroll"))) {
  dataset[, ratio_liquido_sobre_ingresos := msaldo_total_liquido / (mpayroll + 1)]
}

if (atributos_presentes(c("mprestamos_personales", "mactivos_margen"))) {
  dataset[, ratio_prestamos_sobre_activos := mprestamos_personales / (mactivos_margen + 1)]
}

# --- Cambios de status (degradación de categoría) --------------------------------
if (atributos_presentes(c("Visa_status_delta1"))) {
  dataset[, flag_downgrade_visa := as.integer(Visa_status_delta1 < 0)]
}

if (atributos_presentes(c("Master_status_delta1"))) {
  dataset[, flag_downgrade_master := as.integer(Master_status_delta1 < 0)]
}

# --- Interacción entre variables top-Gain -----------------------------------------
if (atributos_presentes(c("ctrx_quarter", "mconsumo_total_tarjetas"))) {
  dataset[, interaccion_ctrx_consumo := ctrx_quarter * mconsumo_total_tarjetas]
}

if (atributos_presentes(c("mcaja_ahorro", "mcuenta_corriente"))) {
  dataset[, ratio_ahorro_corriente := mcaja_ahorro / (mcuenta_corriente + 1)]
}

# ==============================================================================
# EXPERIMENTO 3: Interacciones No Lineales y Polinómicas
# Objetivo: Agregar variables bien construidas que capturen relaciones complejas
# ==============================================================================

# Función auxiliar: log que maneja valores negativos
log_con_signo <- function(x) {
  sign(x) * log1p(abs(x))
}

# --- Interacciones multiplicativas entre variables top ---
vars_top <- c("ctrx_quarter", "mpayroll", "mcaja_ahorro",
              "Visa_msaldototal", "cliente_antiguedad")
vars_top <- intersect(vars_top, colnames(dataset))

cat("Generando interacciones no lineales para:", paste(vars_top, collapse=", "), "\n")

for (i in 1:(length(vars_top)-1)) {
  for (j in (i+1):length(vars_top)) {
    v1 <- vars_top[i]
    v2 <- vars_top[j]
    nombre <- paste0("interaccion_", v1, "_x_", v2)
    
    # Usamos log_con_signo en lugar de log1p directo
    dataset[, (nombre) := log_con_signo(get(v1)) * log_con_signo(get(v2))]
  }
}

# --- Variables polinómicas suaves (también corregidas) ---
if ("ctrx_quarter" %in% colnames(dataset))
  dataset[, ctrx_quarter_suave := ctrx_quarter / (abs(ctrx_quarter) + 100)]

if ("mpayroll" %in% colnames(dataset))
  dataset[, mpayroll_log := log_con_signo(mpayroll)]

cat("Variables nuevas agregadas: 12 (10 interacciones + 2 polinómicas)\n")
cat("Transformación aplicada: sign(x) * log1p(abs(x)) para manejar valores negativos\n")

# --- Bloque Adicional: Transaccionalidad y Comportamiento (ctrx_quarter) ----
if (atributos_presentes(c("ctrx_quarter", "cproductos"))) {
  # Intensidad de uso por producto contratado
  dataset[, ctrx_por_producto := ctrx_quarter / (cproductos + 1)]
}

if (atributos_presentes(c("ctrx_quarter", "mcuenta_corriente"))) {
  # Relación transaccional sobre cuenta corriente
    dataset[, ratio_ctrx_cuentacorriente := ctrx_quarter / (log_con_signo(mcuenta_corriente) + 1)]
    dataset[, uso_descubierto_cc := cdescubierto_preacordado / (log_con_signo(mcuenta_corriente) + 1)]
}

if (atributos_presentes(c("ctrx_quarter", "cpayroll_trx"))) {
  # Flag de transaccionalidad alta sin cobro de sueldo
  dataset[, flag_alta_trx_sin_payroll := as.integer(ctrx_quarter > 20 & cpayroll_trx == 0)]
}

if (atributos_presentes(c("ctrx_quarter", "ctrx_quarter_lag2"))) {
  # Tendencia transaccional a 2 meses
  dataset[, ctrx_delta2 := ctrx_quarter - ctrx_quarter_lag2]
}

# --- Bloque Adicional: Liquidez y Ahorro ------------------------------------
if (atributos_presentes(c("mcaja_ahorro", "msaldo_total_liquido"))) {
  # Proporción que representa la caja de ahorro dentro de la liquidez total
  dataset[, prop_cajaahorro_liquido := mcaja_ahorro / (msaldo_total_liquido + 1)]
}

if (atributos_presentes(c("mcuenta_corriente", "mcaja_ahorro"))) {
  # Balance entre cuenta corriente y caja de ahorro
  dataset[, ratio_cc_vs_ca := (mcuenta_corriente + 1) / (mcaja_ahorro + 1)]
}

if (atributos_presentes(c("mplazo_fijo", "msaldo_total_liquido"))) {
  # Preferencia de inversión frente a liquidez inmediata
  dataset[, ratio_plazofijo_liquido := mplazo_fijo / (msaldo_total_liquido + 1)]
}

if (atributos_presentes(c("mcuentas_saldo", "msaldo_total_liquido"))) {
  # Saldo total en cuentas respecto a liquidez
  dataset[, prop_cuentas_liquido := mcuentas_saldo / (msaldo_total_liquido + 1)]
}

# --- Bloque Adicional: Deuda y Consumo de Tarjetas --------------------------
if (atributos_presentes(c("mtarjeta_visa_consumo", "mtarjeta_master_consumo"))) {
  # Mix de consumo entre tarjetas (franquicia dominante)
  dataset[, ratio_visa_master_consumo := (mtarjeta_visa_consumo + 1) / (mtarjeta_master_consumo + 1)]
}

if (atributos_presentes(c("mtarjeta_visa_consumo", "mtarjeta_visa_limite"))) {
  # Uso del límite asignado en Visa
  dataset[, uso_limite_visa := mtarjeta_visa_consumo / (mtarjeta_visa_limite + 1)]
}

if (atributos_presentes(c("mtarjeta_master_consumo", "mtarjeta_master_limite"))) {
  # Uso del límite asignado en Master
  dataset[, uso_limite_master := mtarjeta_master_consumo / (mtarjeta_master_limite + 1)]
}

if (atributos_presentes(c("mconsumo_total_tarjetas", "mpayroll"))) {
  # Nivel de consumo en tarjetas sobre el ingreso por payroll
  dataset[, ratio_consumo_payroll := mconsumo_total_tarjetas / (mpayroll + 1)]
}



# --- Bloque Adicional: Ingresos y Payroll -----------------------------------
if (atributos_presentes(c("mpayroll", "mpayroll_lag1"))) {
  # Variación directa en el ingreso de sueldo respecto al mes anterior
  dataset[, mpayroll_delta1 := mpayroll - mpayroll_lag1]
}

if (atributos_presentes(c("mpayroll", "mprestamos_personales"))) {
  # Relación préstamo personal frente al ingreso por sueldo
  dataset[, ratio_prestamo_payroll := mprestamos_personales / (mpayroll + 1)]
}

if (atributos_presentes(c("cpayroll_trx", "cpayroll_trx_lag1"))) {
  # Caída o aumento en el conteo de acreditaciones de sueldo
  dataset[, cpayroll_trx_delta1 := cpayroll_trx - cpayroll_trx_lag1]
}

# --- Bloque Adicional: Estado e Inestabilidad de Tarjetas -------------------
if (atributos_presentes(c("Visa_status", "Visa_status_lag1"))) {
  # Deterioro o mejora del estado en tarjeta Visa
  dataset[, visa_status_delta := Visa_status - Visa_status_lag1]
}

if (atributos_presentes(c("Master_status", "Master_status_lag1"))) {
  # Deterioro o mejora del estado en tarjeta Master
  dataset[, master_status_delta := Master_status - Master_status_lag1]
}

if (atributos_presentes(c("Visa_financiacion", "mtarjeta_visa_consumo"))) {
  # Proporción de consumo Visa financiado
  dataset[, prop_visa_financiado := Visa_financiacion / (mtarjeta_visa_consumo + 1)]
}

# --- Bloque Adicional: Ratios Combinados y Deltas Lag -----------------------
if (atributos_presentes(c("mcaja_ahorro", "mcaja_ahorro_lag1"))) {
  # Delta relativo de caja de ahorro
  dataset[, mcaja_ahorro_delta_rel := (mcaja_ahorro - mcaja_ahorro_lag1) / (abs(mcaja_ahorro_lag1) + 1)]
}

if (atributos_presentes(c("mconsumo_total_tarjetas", "mconsumo_total_tarjetas_lag1"))) {
  # Delta relativo de consumo en tarjetas
  dataset[, mconsumo_tarjetas_delta_rel := (mconsumo_total_tarjetas - mconsumo_total_tarjetas_lag1) / (abs(mconsumo_total_tarjetas_lag1) + 1)]
}

if (atributos_presentes(c("cdescubierto_preacordado", "cdescubierto_preacordado_lag1"))) {
  # Cambio de comportamiento en uso de descubierto
  dataset[, cdescubierto_delta1 := cdescubierto_preacordado - cdescubierto_preacordado_lag1]
}

if (atributos_presentes(c("mcomisiones", "ctrx_quarter"))) {
  # Costo por transacción realizada
  dataset[, comisiones_por_trx := mcomisiones / (ctrx_quarter + 1)]
}

if (atributos_presentes(c("mdebito_automatico", "msaldo_total_liquido"))) {
  # Compromiso de débitos automáticos sobre la liquidez
  dataset[, ratio_debitoauto_liquido := mdebito_automatico / (msaldo_total_liquido + 1)]
}

if (atributos_presentes(c("cproductos", "cproductos_lag1"))) {
  # Caída directa en la cantidad de productos (fuga parcial)
  dataset[, cproductos_delta1 := cproductos - cproductos_lag1]
}

Generando interacciones no lineales para: ctrx_quarter, mpayroll, mcaja_ahorro, Visa_msaldototal, cliente_antiguedad
Variables nuevas agregadas: 12 (10 interacciones + 2 polinómicas)
Transformación aplicada: sign(x) * log1p(abs(x)) para manejar valores negativos

In [29]:
# visualizo las columas del dataset a esta etapa
colnames(dataset)

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "internet"
  [4] "cliente_edad"
  [5] "cliente_antiguedad"
  [6] "mrentabilidad"
  [7] "mrentabilidad_annual"
  [8] "mcomisiones"
  [9] "mactivos_margen"
 [10] "mpasivos_margen"
 [11] "cproductos"
 [12] "mcuenta_corriente"
 [13] "mcaja_ahorro"
 [14] "cdescubierto_preacordado"
 [15] "mcuentas_saldo"
 [16] "ctarjeta_visa"
 [17] "ctarjeta_visa_transacciones"
 [18] "mtarjeta_visa_consumo"
 [19] "ctarjeta_master"
 [20] "ctarjeta_master_transacciones"
 [21] "mtarjeta_master_consumo"
 [22] "cprestamos_personales"
 [23] "mprestamos_personales"
 [24] "cpayroll_trx"
 [25] "mpayroll"
 [26] "mttarjeta_visa_debitos_automaticos"
 [27] "ccomisiones_mantenimiento"
 [28] "mcomisiones_mantenimiento"
 [29] "ccomisiones_otras"
 [30] "mtransferencias_recibidas"
 [31] "ccallcenter_transacciones"
 [32] "thomebanking"
 [33] "chomebanking_transacciones"
 [34] "ctrx_quarter"
 [35] "Master_status"
 [36] "Master_mfinanciacion_limite"
 [37] "Master_Fvencimiento"
 [38] "Master_msaldototal"
 [39] "Master_mlimitecompra"
 [40] "Master_fultimo_cierre"
 [41] "Master_fechaalta"
 [42] "Master_mconsumototal"
 [43] "Master_cconsumos"
 [44] "Master_mpagominimo"
 [45] "Visa_status"
 [46] "Visa_mfinanciacion_limite"
 [47] "Visa_Fvencimiento"
 [48] "Visa_msaldototal"
 [49] "Visa_mlimitecompra"
 [50] "Visa_fultimo_cierre"
 [51] "Visa_fechaalta"
 [52] "Visa_mconsumototal"
 [53] "Visa_cconsumos"
 [54] "Visa_mpagominimo"
 [55] "clase_ternaria"
 [56] "kmes"
 [57] "mpayroll_sobre_edad"
 [58] "mconsumo_total_tarjetas"
 [59] "ctrx_total_tarjetas"
 [60] "ratio_visa_pagomin_consumo"
 [61] "ratio_master_pagomin_consumo"
 [62] "ratio_visa_saldo_limite"
 [63] "ratio_master_saldo_limite"
 [64] "msaldo_total_liquido"
 [65] "ratio_cajaahorro_cuentas"
 [66] "ratio_cuentacorriente_cuentas"
 [67] "ratio_consumo_payroll"
 [68] "ratio_prestamos_payroll"
 [69] "mrentabilidad_sobre_payroll"
 [70] "mtransaccion_promedio_quarter"
 [71] "ctrx_por_producto"
 [72] "mrentabilidad_por_producto"
 [73] "mconsumo_promedio_trx_tarjeta"
 [74] "ratio_visa_master_consumo"
 [75] "ratio_uso_limite_total"
 [76] "dias_hasta_vto_visa"
 [77] "dias_hasta_vto_master"
 [78] "ratio_payroll_sobre_rentabilidad"
 [79] "ratio_activos_pasivos"
 [80] "ratio_comisiones_sobre_rentabilidad"
 [81] "antiguedad_sobre_edad"
 [82] "antiguedad_por_producto"
 [83] "flag_inactivo_trimestre"
 [84] "ratio_homebanking_sobre_actividad"
 [85] "ratio_liquido_sobre_ingresos"
 [86] "ratio_prestamos_sobre_activos"
 [87] "interaccion_ctrx_consumo"
 [88] "ratio_ahorro_corriente"
 [89] "interaccion_ctrx_quarter_x_mpayroll"
 [90] "interaccion_ctrx_quarter_x_mcaja_ahorro"
 [91] "interaccion_ctrx_quarter_x_Visa_msaldototal"
 [92] "interaccion_ctrx_quarter_x_cliente_antiguedad"
 [93] "interaccion_mpayroll_x_mcaja_ahorro"
 [94] "interaccion_mpayroll_x_Visa_msaldototal"
 [95] "interaccion_mpayroll_x_cliente_antiguedad"
 [96] "interaccion_mcaja_ahorro_x_Visa_msaldototal"
 [97] "interaccion_mcaja_ahorro_x_cliente_antiguedad"
 [98] "interaccion_Visa_msaldototal_x_cliente_antiguedad"
 [99] "ctrx_quarter_suave"
[100] "mpayroll_log"
[101] "ratio_ctrx_cuentacorriente"
[102] "uso_descubierto_cc"
[103] "flag_alta_trx_sin_payroll"
[104] "prop_cajaahorro_liquido"
[105] "ratio_cc_vs_ca"
[106] "prop_cuentas_liquido"
[107] "ratio_prestamo_payroll"
[108] "comisiones_por_trx"

#### 9.3.1.4  FE_rf Feature Engineering de nuevas variables a partir de hojas de Random Forest

In [30]:
# No se implementa Feature Engineering a partir de Random Forest

#### 9.3.1.5  FEhist Feature Engineering historico

El Fature Engineering Histórico es la etapa que más aporta a la ganancia final, ya que enriquece cada registro del dataset con su historia.

Para cada campo del dataset original (*)
se crean lo siguientes campos de a partir de la historia
* lag1  lags de orden 1
* delta1  =  valor actual - lag1
* lag2  lags de orden 2
* delta2  = valor actual - lag2


(*) Excepto para los campos  <numero_de_cliente,  foto_mes,  clase_ternaria>

In [31]:
# Feature Engineering Historico

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente", "foto_mes", "clase_ternaria")
) )

# https://rdrr.io/cran/data.table/man/shift.html

# lags de orden 1
dataset[,
    paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# lags de orden 2
dataset[,
    paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# agrego los delta lags
for (vcol in cols_lagueables)
{
    dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
    dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}

Verificacion de los campos recien creados

In [32]:
ncol(dataset)
colnames(dataset)

[1] 528

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "internet"
  [4] "cliente_edad"
  [5] "cliente_antiguedad"
  [6] "mrentabilidad"
  [7] "mrentabilidad_annual"
  [8] "mcomisiones"
  [9] "mactivos_margen"
 [10] "mpasivos_margen"
 [11] "cproductos"
 [12] "mcuenta_corriente"
 [13] "mcaja_ahorro"
 [14] "cdescubierto_preacordado"
 [15] "mcuentas_saldo"
 [16] "ctarjeta_visa"
 [17] "ctarjeta_visa_transacciones"
 [18] "mtarjeta_visa_consumo"
 [19] "ctarjeta_master"
 [20] "ctarjeta_master_transacciones"
 [21] "mtarjeta_master_consumo"
 [22] "cprestamos_personales"
 [23] "mprestamos_personales"
 [24] "cpayroll_trx"
 [25] "mpayroll"
 [26] "mttarjeta_visa_debitos_automaticos"
 [27] "ccomisiones_mantenimiento"
 [28] "mcomisiones_mantenimiento"
 [29] "ccomisiones_otras"
 [30] "mtransferencias_recibidas"
 [31] "ccallcenter_transacciones"
 [32] "thomebanking"
 [33] "chomebanking_transacciones"
 [34] "ctrx_quarter"
 [35] "Master_status"
 [36] "Master_mfinanciacion_limite"
 [37] "Master_Fvencimiento"
 [38] "Master_msaldototal"
 [39] "Master_mlimitecompra"
 [40] "Master_fultimo_cierre"
 [41] "Master_fechaalta"
 [42] "Master_mconsumototal"
 [43] "Master_cconsumos"
 [44] "Master_mpagominimo"
 [45] "Visa_status"
 [46] "Visa_mfinanciacion_limite"
 [47] "Visa_Fvencimiento"
 [48] "Visa_msaldototal"
 [49] "Visa_mlimitecompra"
 [50] "Visa_fultimo_cierre"
 [51] "Visa_fechaalta"
 [52] "Visa_mconsumototal"
 [53] "Visa_cconsumos"
 [54] "Visa_mpagominimo"
 [55] "clase_ternaria"
 [56] "kmes"
 [57] "mpayroll_sobre_edad"
 [58] "mconsumo_total_tarjetas"
 [59] "ctrx_total_tarjetas"
 [60] "ratio_visa_pagomin_consumo"
 [61] "ratio_master_pagomin_consumo"
 [62] "ratio_visa_saldo_limite"
 [63] "ratio_master_saldo_limite"
 [64] "msaldo_total_liquido"
 [65] "ratio_cajaahorro_cuentas"
 [66] "ratio_cuentacorriente_cuentas"
 [67] "ratio_consumo_payroll"
 [68] "ratio_prestamos_payroll"
 [69] "mrentabilidad_sobre_payroll"
 [70] "mtransaccion_promedio_quarter"
 [71] "ctrx_por_producto"
 [72] "mrentabilidad_por_producto"
 [73] "mconsumo_promedio_trx_tarjeta"
 [74] "ratio_visa_master_consumo"
 [75] "ratio_uso_limite_total"
 [76] "dias_hasta_vto_visa"
 [77] "dias_hasta_vto_master"
 [78] "ratio_payroll_sobre_rentabilidad"
 [79] "ratio_activos_pasivos"
 [80] "ratio_comisiones_sobre_rentabilidad"
 [81] "antiguedad_sobre_edad"
 [82] "antiguedad_por_producto"
 [83] "flag_inactivo_trimestre"
 [84] "ratio_homebanking_sobre_actividad"
 [85] "ratio_liquido_sobre_ingresos"
 [86] "ratio_prestamos_sobre_activos"
 [87] "interaccion_ctrx_consumo"
 [88] "ratio_ahorro_corriente"
 [89] "interaccion_ctrx_quarter_x_mpayroll"
 [90] "interaccion_ctrx_quarter_x_mcaja_ahorro"
 [91] "interaccion_ctrx_quarter_x_Visa_msaldototal"
 [92] "interaccion_ctrx_quarter_x_cliente_antiguedad"
 [93] "interaccion_mpayroll_x_mcaja_ahorro"
 [94] "interaccion_mpayroll_x_Visa_msaldototal"
 [95] "interaccion_mpayroll_x_cliente_antiguedad"
 [96] "interaccion_mcaja_ahorro_x_Visa_msaldototal"
 [97] "interaccion_mcaja_ahorro_x_cliente_antiguedad"
 [98] "interaccion_Visa_msaldototal_x_cliente_antiguedad"
 [99] "ctrx_quarter_suave"
[100] "mpayroll_log"
[101] "ratio_ctrx_cuentacorriente"
[102] "uso_descubierto_cc"
[103] "flag_alta_trx_sin_payroll"
[104] "prop_cajaahorro_liquido"
[105] "ratio_cc_vs_ca"
[106] "prop_cuentas_liquido"
[107] "ratio_prestamo_payroll"
[108] "comisiones_por_trx"
[109] "internet_lag1"
[110] "cliente_edad_lag1"
[111] "cliente_antiguedad_lag1"
[112] "mrentabilidad_lag1"
[113] "mrentabilidad_annual_lag1"
[114] "mcomisiones_lag1"
[115] "mactivos_margen_lag1"
[116] "mpasivos_margen_lag1"
[117] "cproductos_lag1"
[118] "mcuenta_corriente_lag1"
[119] "mcaja_ahorro_lag1"
[120] "cdescubierto_preacordado_lag1"
[121] "mcuentas_saldo_lag1"
[122] "ctarjeta_visa_lag1"
[123] "ctarjeta_visa_transacciones_lag1"
[124] "mtarjeta_visa_consumo_lag1"
[125] "ctarjeta_master_lag1"
[126] "ctarjeta_master_transacciones_lag1"
[127] "mtarjeta_master_consumo_lag1"
[128] "cprestamos_personales_lag1"
[129] "mprestamos_personales_lag1"
[130] "cpayroll_trx_lag1"
[131] "mpayroll_lag1"
[132] "mttarjeta_visa_debitos_automaticos_lag1"
[133] "ccomisiones_mantenimiento_lag1"
[134] "mcomisiones_mantenimiento_lag1"
[135] "ccomisiones_otras_lag1"
[136] "mtransferencias_recibidas_lag1"
[137] "ccallcenter_transacciones_lag1"
[138] "thomebanking_lag1"
[139] "chomebanking_transacciones_lag1"
[140] "ctrx_quarter_lag1"
[141] "Master_status_lag1"
[142] "Master_mfinanciacion_limite_lag1"
[143] "Master_Fvencimiento_lag1"
[144] "Master_msaldototal_lag1"
[145] "Master_mlimitecompra_lag1"
[146] "Master_fultimo_cierre_lag1"
[147] "Master_fechaalta_lag1"
[148] "Master_mconsumototal_lag1"
[149] "Master_cconsumos_lag1"
[150] "Master_mpagominimo_lag1"
[151] "Visa_status_lag1"
[152] "Visa_mfinanciacion_limite_lag1"
[153] "Visa_Fvencimiento_lag1"
[154] "Visa_msaldototal_lag1"
[155] "Visa_mlimitecompra_lag1"
[156] "Visa_fultimo_cierre_lag1"
[157] "Visa_fechaalta_lag1"
[158] "Visa_mconsumototal_lag1"
[159] "Visa_cconsumos_lag1"
[160] "Visa_mpagominimo_lag1"
[161] "kmes_lag1"
[162] "mpayroll_sobre_edad_lag1"
[163] "mconsumo_total_tarjetas_lag1"
[164] "ctrx_total_tarjetas_lag1"
[165] "ratio_visa_pagomin_consumo_lag1"
[166] "ratio_master_pagomin_consumo_lag1"
[167] "ratio_visa_saldo_limite_lag1"
[168] "ratio_master_saldo_limite_lag1"
[169] "msaldo_total_liquido_lag1"
[170] "ratio_cajaahorro_cuentas_lag1"
[171] "ratio_cuentacorriente_cuentas_lag1"
[172] "ratio_consumo_payroll_lag1"
[173] "ratio_prestamos_payroll_lag1"
[174] "mrentabilidad_sobre_payroll_lag1"
[175] "mtransaccion_promedio_quarter_lag1"
[176] "ctrx_por_producto_lag1"
[177] "mrentabilidad_por_producto_lag1"
[178] "mconsumo_promedio_trx_tarjeta_lag1"
[179] "ratio_visa_master_consumo_lag1"
[180] "ratio_uso_limite_total_lag1"
[181] "dias_hasta_vto_visa_lag1"
[182] "dias_hasta_vto_master_lag1"
[183] "ratio_payroll_sobre_rentabilidad_lag1"
[184] "ratio_activos_pasivos_lag1"
[185] "ratio_comisiones_sobre_rentabilidad_lag1"
[186] "antiguedad_sobre_edad_lag1"
[187] "antiguedad_por_producto_lag1"
[188] "flag_inactivo_trimestre_lag1"
[189] "ratio_homebanking_sobre_actividad_lag1"
[190] "ratio_liquido_sobre_ingresos_lag1"
[191] "ratio_prestamos_sobre_activos_lag1"
[192] "interaccion_ctrx_consumo_lag1"
[193] "ratio_ahorro_corriente_lag1"
[194] "interaccion_ctrx_quarter_x_mpayroll_lag1"
[195] "interaccion_ctrx_quarter_x_mcaja_ahorro_lag1"
[196] "interaccion_ctrx_quarter_x_Visa_msaldototal_lag1"
[197] "interaccion_ctrx_quarter_x_cliente_antiguedad_lag1"
[198] "interaccion_mpayroll_x_mcaja_ahorro_lag1"
[199] "interaccion_mpayroll_x_Visa_msaldototal_lag1"
[200] "interaccion_mpayroll_x_cliente_antiguedad_lag1"
[201] "interaccion_mcaja_ahorro_x_Visa_msaldototal_lag1"
[202] "interaccion_mcaja_ahorro_x_cliente_antiguedad_lag1"
[203] "interaccion_Visa_msaldototal_x_cliente_antiguedad_lag1"
[204] "ctrx_quarter_suave_lag1"
[205] "mpayroll_log_lag1"
[206] "ratio_ctrx_cuentacorriente_lag1"
[207] "uso_descubierto_cc_lag1"
[208] "flag_alta_trx_sin_payroll_lag1"
[209] "prop_cajaahorro_liquido_lag1"
[210] "ratio_cc_vs_ca_lag1"
[211] "prop_cuentas_liquido_lag1"
[212] "ratio_prestamo_payroll_lag1"
[213] "comisiones_por_trx_lag1"
[214] "internet_lag2"
[215] "cliente_edad_lag2"
[216] "cliente_antiguedad_lag2"
[217] "mrentabilidad_lag2"
[218] "mrentabilidad_annual_lag2"
[219] "mcomisiones_lag2"
[220] "mactivos_margen_lag2"
[221] "mpasivos_margen_lag2"
[222] "cproductos_lag2"
[223] "mcuenta_corriente_lag2"
[224] "mcaja_ahorro_lag2"
[225] "cdescubierto_preacordado_lag2"
[226] "mcuentas_saldo_lag2"
[227] "ctarjeta_visa_lag2"
[228] "ctarjeta_visa_transacciones_lag2"
[229] "mtarjeta_visa_consumo_lag2"
[230] "ctarjeta_master_lag2"
[231] "ctarjeta_master_transacciones_lag2"
[232] "mtarjeta_master_consumo_lag2"
[233] "cprestamos_personales_lag2"
[234] "mprestamos_personales_lag2"
[235] "cpayroll_trx_lag2"
[236] "mpayroll_lag2"
[237] "mttarjeta_visa_debitos_automaticos_lag2"
[238] "ccomisiones_mantenimiento_lag2"
[239] "mcomisiones_mantenimiento_lag2"
[240] "ccomisiones_otras_lag2"
[241] "mtransferencias_recibidas_lag2"
[242] "ccallcenter_transacciones_lag2"
[243] "thomebanking_lag2"
[244] "chomebanking_transacciones_lag2"
[245] "ctrx_quarter_lag2"
[246] "Master_status_lag2"
[247] "Master_mfinanciacion_limite_lag2"
[248] "Master_Fvencimiento_lag2"
[249] "Master_msaldototal_lag2"
[250] "Master_mlimitecompra_lag2"
[251] "Master_fultimo_cierre_lag2"
[252] "Master_fechaalta_lag2"
[253] "Master_mconsumototal_lag2"
[254] "Master_cconsumos_lag2"
[255] "Master_mpagominimo_lag2"
[256] "Visa_status_lag2"
[257] "Visa_mfinanciacion_limite_lag2"
[258] "Visa_Fvencimiento_lag2"
[259] "Visa_msaldototal_lag2"
[260] "Visa_mlimitecompra_lag2"
[261] "Visa_fultimo_cierre_lag2"
[262] "Visa_fechaalta_lag2"
[263] "Visa_mconsumototal_lag2"
[264] "Visa_cconsumos_lag2"
[265] "Visa_mpagominimo_lag2"
[266] "kmes_lag2"
[267] "mpayroll_sobre_edad_lag2"
[268] "mconsumo_total_tarjetas_lag2"
[269] "ctrx_total_tarjetas_lag2"
[270] "ratio_visa_pagomin_consumo_lag2"
[271] "ratio_master_pagomin_consumo_lag2"
[272] "ratio_visa_saldo_limite_lag2"
[273] "ratio_master_saldo_limite_lag2"
[274] "msaldo_total_liquido_lag2"
[275] "ratio_cajaahorro_cuentas_lag2"
[276] "ratio_cuentacorriente_cuentas_lag2"
[277] "ratio_consumo_payroll_lag2"
[278] "ratio_prestamos_payroll_lag2"
[279] "mrentabilidad_sobre_payroll_lag2"
[280] "mtransaccion_promedio_quarter_lag2"
[281] "ctrx_por_producto_lag2"
[282] "mrentabilidad_por_producto_lag2"
[283] "mconsumo_promedio_trx_tarjeta_lag2"
[284] "ratio_visa_master_consumo_lag2"
[285] "ratio_uso_limite_total_lag2"
[286] "dias_hasta_vto_visa_lag2"
[287] "dias_hasta_vto_master_lag2"
[288] "ratio_payroll_sobre_rentabilidad_lag2"
[289] "ratio_activos_pasivos_lag2"
[290] "ratio_comisiones_sobre_rentabilidad_lag2"
[291] "antiguedad_sobre_edad_lag2"
[292] "antiguedad_por_producto_lag2"
[293] "flag_inactivo_trimestre_lag2"
[294] "ratio_homebanking_sobre_actividad_lag2"
[295] "ratio_liquido_sobre_ingresos_lag2"
[296] "ratio_prestamos_sobre_activos_lag2"
[297] "interaccion_ctrx_consumo_lag2"
[298] "ratio_ahorro_corriente_lag2"
[299] "interaccion_ctrx_quarter_x_mpayroll_lag2"
[300] "interaccion_ctrx_quarter_x_mcaja_ahorro_lag2"
[301] "interaccion_ctrx_quarter_x_Visa_msaldototal_lag2"
[302] "interaccion_ctrx_quarter_x_cliente_antiguedad_lag2"
[303] "interaccion_mpayroll_x_mcaja_ahorro_lag2"
[304] "interaccion_mpayroll_x_Visa_msaldototal_lag2"
[305] "interaccion_mpayroll_x_cliente_antiguedad_lag2"
[306] "interaccion_mcaja_ahorro_x_Visa_msaldototal_lag2"
[307] "interaccion_mcaja_ahorro_x_cliente_antiguedad_lag2"
[308] "interaccion_Visa_msaldototal_x_cliente_antiguedad_lag2"
[309] "ctrx_quarter_suave_lag2"
[310] "mpayroll_log_lag2"
[311] "ratio_ctrx_cuentacorriente_lag2"
[312] "uso_descubierto_cc_lag2"
[313] "flag_alta_trx_sin_payroll_lag2"
[314] "prop_cajaahorro_liquido_lag2"
[315] "ratio_cc_vs_ca_lag2"
[316] "prop_cuentas_liquido_lag2"
[317] "ratio_prestamo_payroll_lag2"
[318] "comisiones_por_trx_lag2"
[319] "internet_delta1"
[320] "internet_delta2"
[321] "cliente_edad_delta1"
[322] "cliente_edad_delta2"
[323] "cliente_antiguedad_delta1"
[324] "cliente_antiguedad_delta2"
[325] "mrentabilidad_delta1"
[326] "mrentabilidad_delta2"
[327] "mrentabilidad_annual_delta1"
[328] "mrentabilidad_annual_delta2"
[329] "mcomisiones_delta1"
[330] "mcomisiones_delta2"
[331] "mactivos_margen_delta1"
[332] "mactivos_margen_delta2"
[333] "mpasivos_margen_delta1"
[334] "mpasivos_margen_delta2"
[335] "cproductos_delta1"
[336] "cproductos_delta2"
[337] "mcuenta_corriente_delta1"
[338] "mcuenta_corriente_delta2"
[339] "mcaja_ahorro_delta1"
[340] "mcaja_ahorro_delta2"
[341] "cdescubierto_preacordado_delta1"
[342] "cdescubierto_preacordado_delta2"
[343] "mcuentas_saldo_delta1"
[344] "mcuentas_saldo_delta2"
[345] "ctarjeta_visa_delta1"
[346] "ctarjeta_visa_delta2"
[347] "ctarjeta_visa_transacciones_delta1"
[348] "ctarjeta_visa_transacciones_delta2"
[349] "mtarjeta_visa_consumo_delta1"
[350] "mtarjeta_visa_consumo_delta2"
[351] "ctarjeta_master_delta1"
[352] "ctarjeta_master_delta2"
[353] "ctarjeta_master_transacciones_delta1"
[354] "ctarjeta_master_transacciones_delta2"
[355] "mtarjeta_master_consumo_delta1"
[356] "mtarjeta_master_consumo_delta2"
[357] "cprestamos_personales_delta1"
[358] "cprestamos_personales_delta2"
[359] "mprestamos_personales_delta1"
[360] "mprestamos_personales_delta2"
[361] "cpayroll_trx_delta1"
[362] "cpayroll_trx_delta2"
[363] "mpayroll_delta1"
[364] "mpayroll_delta2"
[365] "mttarjeta_visa_debitos_automaticos_delta1"
[366] "mttarjeta_visa_debitos_automaticos_delta2"
[367] "ccomisiones_mantenimiento_delta1"
[368] "ccomisiones_mantenimiento_delta2"
[369] "mcomisiones_mantenimiento_delta1"
[370] "mcomisiones_mantenimiento_delta2"
[371] "ccomisiones_otras_delta1"
[372] "ccomisiones_otras_delta2"
[373] "mtransferencias_recibidas_delta1"
[374] "mtransferencias_recibidas_delta2"
[375] "ccallcenter_transacciones_delta1"
[376] "ccallcenter_transacciones_delta2"
[377] "thomebanking_delta1"
[378] "thomebanking_delta2"
[379] "chomebanking_transacciones_delta1"
[380] "chomebanking_transacciones_delta2"
[381] "ctrx_quarter_delta1"
[382] "ctrx_quarter_delta2"
[383] "Master_status_delta1"
[384] "Master_status_delta2"
[385] "Master_mfinanciacion_limite_delta1"
[386] "Master_mfinanciacion_limite_delta2"
[387] "Master_Fvencimiento_delta1"
[388] "Master_Fvencimiento_delta2"
[389] "Master_msaldototal_delta1"
[390] "Master_msaldototal_delta2"
[391] "Master_mlimitecompra_delta1"
[392] "Master_mlimitecompra_delta2"
[393] "Master_fultimo_cierre_delta1"
[394] "Master_fultimo_cierre_delta2"
[395] "Master_fechaalta_delta1"
[396] "Master_fechaalta_delta2"
[397] "Master_mconsumototal_delta1"
[398] "Master_mconsumototal_delta2"
[399] "Master_cconsumos_delta1"
[400] "Master_cconsumos_delta2"
[401] "Master_mpagominimo_delta1"
[402] "Master_mpagominimo_delta2"
[403] "Visa_status_delta1"
[404] "Visa_status_delta2"
[405] "Visa_mfinanciacion_limite_delta1"
[406] "Visa_mfinanciacion_limite_delta2"
[407] "Visa_Fvencimiento_delta1"
[408] "Visa_Fvencimiento_delta2"
[409] "Visa_msaldototal_delta1"
[410] "Visa_msaldototal_delta2"
[411] "Visa_mlimitecompra_delta1"
[412] "Visa_mlimitecompra_delta2"
[413] "Visa_fultimo_cierre_delta1"
[414] "Visa_fultimo_cierre_delta2"
[415] "Visa_fechaalta_delta1"
[416] "Visa_fechaalta_delta2"
[417] "Visa_mconsumototal_delta1"
[418] "Visa_mconsumototal_delta2"
[419] "Visa_cconsumos_delta1"
[420] "Visa_cconsumos_delta2"
[421] "Visa_mpagominimo_delta1"
[422] "Visa_mpagominimo_delta2"
[423] "kmes_delta1"
[424] "kmes_delta2"
[425] "mpayroll_sobre_edad_delta1"
[426] "mpayroll_sobre_edad_delta2"
[427] "mconsumo_total_tarjetas_delta1"
[428] "mconsumo_total_tarjetas_delta2"
[429] "ctrx_total_tarjetas_delta1"
[430] "ctrx_total_tarjetas_delta2"
[431] "ratio_visa_pagomin_consumo_delta1"
[432] "ratio_visa_pagomin_consumo_delta2"
[433] "ratio_master_pagomin_consumo_delta1"
[434] "ratio_master_pagomin_consumo_delta2"
[435] "ratio_visa_saldo_limite_delta1"
[436] "ratio_visa_saldo_limite_delta2"
[437] "ratio_master_saldo_limite_delta1"
[438] "ratio_master_saldo_limite_delta2"
[439] "msaldo_total_liquido_delta1"
[440] "msaldo_total_liquido_delta2"
[441] "ratio_cajaahorro_cuentas_delta1"
[442] "ratio_cajaahorro_cuentas_delta2"
[443] "ratio_cuentacorriente_cuentas_delta1"
[444] "ratio_cuentacorriente_cuentas_delta2"
[445] "ratio_consumo_payroll_delta1"
[446] "ratio_consumo_payroll_delta2"
[447] "ratio_prestamos_payroll_delta1"
[448] "ratio_prestamos_payroll_delta2"
[449] "mrentabilidad_sobre_payroll_delta1"
[450] "mrentabilidad_sobre_payroll_delta2"
[451] "mtransaccion_promedio_quarter_delta1"
[452] "mtransaccion_promedio_quarter_delta2"
[453] "ctrx_por_producto_delta1"
[454] "ctrx_por_producto_delta2"
[455] "mrentabilidad_por_producto_delta1"
[456] "mrentabilidad_por_producto_delta2"
[457] "mconsumo_promedio_trx_tarjeta_delta1"
[458] "mconsumo_promedio_trx_tarjeta_delta2"
[459] "ratio_visa_master_consumo_delta1"
[460] "ratio_visa_master_consumo_delta2"
[461] "ratio_uso_limite_total_delta1"
[462] "ratio_uso_limite_total_delta2"
[463] "dias_hasta_vto_visa_delta1"
[464] "dias_hasta_vto_visa_delta2"
[465] "dias_hasta_vto_master_delta1"
[466] "dias_hasta_vto_master_delta2"
[467] "ratio_payroll_sobre_rentabilidad_delta1"
[468] "ratio_payroll_sobre_rentabilidad_delta2"
[469] "ratio_activos_pasivos_delta1"
[470] "ratio_activos_pasivos_delta2"
[471] "ratio_comisiones_sobre_rentabilidad_delta1"
[472] "ratio_comisiones_sobre_rentabilidad_delta2"
[473] "antiguedad_sobre_edad_delta1"
[474] "antiguedad_sobre_edad_delta2"
[475] "antiguedad_por_producto_delta1"
[476] "antiguedad_por_producto_delta2"
[477] "flag_inactivo_trimestre_delta1"
[478] "flag_inactivo_trimestre_delta2"
[479] "ratio_homebanking_sobre_actividad_delta1"
[480] "ratio_homebanking_sobre_actividad_delta2"
[481] "ratio_liquido_sobre_ingresos_delta1"
[482] "ratio_liquido_sobre_ingresos_delta2"
[483] "ratio_prestamos_sobre_activos_delta1"
[484] "ratio_prestamos_sobre_activos_delta2"
[485] "interaccion_ctrx_consumo_delta1"
[486] "interaccion_ctrx_consumo_delta2"
[487] "ratio_ahorro_corriente_delta1"
[488] "ratio_ahorro_corriente_delta2"
[489] "interaccion_ctrx_quarter_x_mpayroll_delta1"
[490] "interaccion_ctrx_quarter_x_mpayroll_delta2"
[491] "interaccion_ctrx_quarter_x_mcaja_ahorro_delta1"
[492] "interaccion_ctrx_quarter_x_mcaja_ahorro_delta2"
[493] "interaccion_ctrx_quarter_x_Visa_msaldototal_delta1"
[494] "interaccion_ctrx_quarter_x_Visa_msaldototal_delta2"
[495] "interaccion_ctrx_quarter_x_cliente_antiguedad_delta1"
[496] "interaccion_ctrx_quarter_x_cliente_antiguedad_delta2"
[497] "interaccion_mpayroll_x_mcaja_ahorro_delta1"
[498] "interaccion_mpayroll_x_mcaja_ahorro_delta2"
[499] "interaccion_mpayroll_x_Visa_msaldototal_delta1"
[500] "interaccion_mpayroll_x_Visa_msaldototal_delta2"
[501] "interaccion_mpayroll_x_cliente_antiguedad_delta1"
[502] "interaccion_mpayroll_x_cliente_antiguedad_delta2"
[503] "interaccion_mcaja_ahorro_x_Visa_msaldototal_delta1"
[504] "interaccion_mcaja_ahorro_x_Visa_msaldototal_delta2"
[505] "interaccion_mcaja_ahorro_x_cliente_antiguedad_delta1"
[506] "interaccion_mcaja_ahorro_x_cliente_antiguedad_delta2"
[507] "interaccion_Visa_msaldototal_x_cliente_antiguedad_delta1"
[508] "interaccion_Visa_msaldototal_x_cliente_antiguedad_delta2"
[509] "ctrx_quarter_suave_delta1"
[510] "ctrx_quarter_suave_delta2"
[511] "mpayroll_log_delta1"
[512] "mpayroll_log_delta2"
[513] "ratio_ctrx_cuentacorriente_delta1"
[514] "ratio_ctrx_cuentacorriente_delta2"
[515] "uso_descubierto_cc_delta1"
[516] "uso_descubierto_cc_delta2"
[517] "flag_alta_trx_sin_payroll_delta1"
[518] "flag_alta_trx_sin_payroll_delta2"
[519] "prop_cajaahorro_liquido_delta1"
[520] "prop_cajaahorro_liquido_delta2"
[521] "ratio_cc_vs_ca_delta1"
[522] "ratio_cc_vs_ca_delta2"
[523] "prop_cuentas_liquido_delta1"
[524] "prop_cuentas_liquido_delta2"
[525] "ratio_prestamo_payroll_delta1"
[526] "ratio_prestamo_payroll_delta2"
[527] "comisiones_por_trx_delta1"
[528] "comisiones_por_trx_delta2"

#### 9.3.1.6  FEhist Reduccion dimensionalidad con canaritos

Esta etapa solo se mostrará a la *modalidad Anlista Sr* por algun canal secreto de forma de no confundir a los *Analista Jr*  ni distraer con detalles operativos a la estratégica *Modalidad Gerencial*

In [33]:
# No se implementa la reduccion de la dimensionalidad con canaritos

#### 9.3.2 Modelado - LOOP DE 10 SEMILLAS

* Hiperparametros 
  * num_leaves = 64
  * min_data_in_leaf = 128
  * feature_fraction = 0.5
  * learning_rate = 0.03

In [34]:
semillas <- c(146023, 419921, 453601,906313,994481, 100003, 200003, 300007, 400009, 500009)

# Contenedor para los resultados de cada semilla
tb_resultado_semillas <- data.table(
  semilla = integer(),
  AUC_grid = numeric(),
  mejores_hiperparametros = list()
)

# ============================================================================
# 9.3.2.1 Training Strategy (COMUN a todas las semillas)
# ============================================================================

PARAM$trainingstrategy$validate  <- c(202107)

PARAM$trainingstrategy$training  <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)

PARAM$trainingstrategy$training_pct  <- 1.0
PARAM$trainingstrategy$positivos  <- c("BAJA+1", "BAJA+2")

PARAM$trainingstrategy$final_train  <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107
)

PARAM$trainingstrategy$future  <- c(202109)

# clase01 (una sola vez, no depende de la semilla)
dataset[, clase01 := ifelse(clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0)]

# campos buenos (una sola vez)
campos_buenos  <- copy(setdiff(
  colnames(dataset), c("clase_ternaria", "clase01", "azar", "numero_de_cliente")
))

# fold_final_train (una sola vez)
dataset[, fold_final_train := foto_mes %in% PARAM$trainingstrategy$final_train]

# dfuture (una sola vez)
dfuture  <- dataset[foto_mes %in% PARAM$trainingstrategy$future]

if (!require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

# Kaggle setup (una sola vez)
PARAM$kaggle$competencia  <- "utn-2026-virtual-jr"
PARAM$kaggle$cortes  <- seq(1800, 2400, by = 100)
dir.create("kaggle", showWarnings = FALSE)

# ============================================================================
# LOOP PRINCIPAL: una iteracion por cada semilla
# ============================================================================

for (i_semilla in seq_along(semillas)) {
  
  semilla_actual <- semillas[i_semilla]
  cat("\n\n")
  cat("============================================================\n")
  cat(sprintf("  SEMILLA %d de %d  -->  %d\n", i_semilla, length(semillas), semilla_actual))
  cat("============================================================\n")
  cat(format(Sys.time(), "%a %b %d %X %Y\n"))
  
  # Actualizo la semilla y el experimento en PARAM
  PARAM$semilla_primigenia <- semilla_actual
  PARAM$experimento <- 9300 + i_semilla  # 9101, 9102, 9103, 9104, 9105
  
  # ------------------------------------------------------------------
  # 1) azar + fold_train (depende de la semilla)
  # ------------------------------------------------------------------
  set.seed(semilla_actual, kind = "L'Ecuyer-CMRG")
  dataset[, azar := runif(nrow(dataset))]
  
  dataset[, fold_train := foto_mes %in% PARAM$trainingstrategy$training &
    (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
     azar < PARAM$trainingstrategy$training_pct)]
  
  # ------------------------------------------------------------------
  # 2) dtrain y dvalidate (se reconstruyen con la nueva semilla)
  # ------------------------------------------------------------------
  dtrain <- lgb.Dataset(
    data = data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
    label = dataset[fold_train == TRUE, clase01],
    free_raw_data = TRUE
  )
  
  dvalidate <- lgb.Dataset(
    data = data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
    label = dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
    free_raw_data = TRUE
  )
  
  # ------------------------------------------------------------------
  # 3) Parametros fijos de LightGBM (con la semilla actual)
  # ------------------------------------------------------------------
  PARAM$lgbm$param_fijos <- list(
    objective = "binary",
    metric = "auc",
    first_metric_only = TRUE,
    boost_from_average = TRUE,
    feature_pre_filter = FALSE,
    verbosity = -100,
    force_row_wise = TRUE,
    seed = semilla_actual,
    max_bin = 31,
    learning_rate = 0.03,
    feature_fraction = 0.5,
    num_iterations = 2048,
    early_stopping_rounds = 200,
    num_leaves = 64,
    min_data_in_leaf = 128
  )
  
  # ------------------------------------------------------------------
  # 4) Funcion Estimar_AUC_lightgbm
  # ------------------------------------------------------------------
  Estimar_AUC_lightgbm <- function(x) {
    param_completo <- modifyList(PARAM$lgbm$param_fijos, x)
    
    modelo_train <- lgb.train(
      data = dtrain,
      valids = list(valid = dvalidate),
      eval = "auc",
      param = param_completo,
      verbose = -100
    )
    
    AUC <- modelo_train$record_evals$valid$auc$eval[[modelo_train$best_iter]]
    niter <- modelo_train$best_iter
    
    rm(modelo_train)
    gc(full = TRUE, verbose = FALSE)
    
    return(list(AUC, niter))
  }
  
  # ------------------------------------------------------------------
  # 5) GRID SEARCH (~65 min por semilla)
  # ------------------------------------------------------------------
  cat("\n--- Grid Search para semilla", semilla_actual, "---\n")
  cat(format(Sys.time(), "Inicio: %a %b %d %X %Y\n"))
  
  tb_nueva <- CJ(
    num_leaves = c(64),
    min_data_in_leaf = c(128),
    feature_fraction = c(0.5)
  )
  
  tb_nueva[, c("AUC", "num_iterations") := Estimar_AUC_lightgbm(.SD),
    by = 1:nrow(tb_nueva)]
  
  fwrite(tb_nueva,
    file = sprintf("tb_grid_search_semilla_%d.txt", semilla_actual),
    sep = "\t")
  
  setorder(tb_nueva, -AUC)
  
  AUC_mejor <- tb_nueva[1, AUC]
  mejores_hp <- as.list(tb_nueva[1])
  mejores_hp$AUC <- NULL
  
  cat(sprintf("\nMejor AUC semilla %d: %.6f\n", semilla_actual, AUC_mejor))
  print(mejores_hp)
  
  # Guardo resultado de esta semilla
  tb_resultado_semillas <- rbind(tb_resultado_semillas,
    data.table(
      semilla = semilla_actual,
      AUC_grid = AUC_mejor,
      mejores_hiperparametros = list(mejores_hp)
    ))
  
  # ------------------------------------------------------------------
  # 6) FINAL TRAINING
  # ------------------------------------------------------------------
  cat("\n--- Final Training para semilla", semilla_actual, "---\n")
  
  dfinal_train <- lgb.Dataset(
    data = data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with = FALSE]),
    label = dataset[fold_final_train == TRUE, clase01],
    free_raw_data = TRUE
  )
  
  fijos <- copy(PARAM$lgbm$param_fijos)
  fijos$num_iterations <- NULL
  fijos$early_stopping_rounds <- NULL
  
  param_final <- c(fijos, mejores_hp)
  
  final_model <- lgb.train(
    data = dfinal_train,
    param = param_final,
    verbose = -100
  )
  
  lgb.save(final_model, sprintf("modelo_semilla_%d.txt", semilla_actual))
  
  tb_importancia <- as.data.table(lgb.importance(final_model))
  fwrite(tb_importancia,
    file = sprintf("importancia_semilla_%d.txt", semilla_actual),
    sep = "\t")
  
  # ------------------------------------------------------------------
  # 7) SCORING sobre future
  # ------------------------------------------------------------------
  prediccion <- predict(
    final_model,
    data.matrix(dfuture[, campos_buenos, with = FALSE])
  )
  
  tb_prediccion <- dfuture[, list(numero_de_cliente)]
  tb_prediccion[, prob := prediccion]
  
  fwrite(tb_prediccion,
    file = sprintf("prediccion_semilla_%d.txt", semilla_actual),
    sep = "\t")
  
  # ------------------------------------------------------------------
  # 8) SUBMITS A KAGGLE (7 cortes)
  # ------------------------------------------------------------------
  cat("\n--- Submits a Kaggle para semilla", semilla_actual, "---\n")
  
  setorder(tb_prediccion, -prob)
  
  for (envios in PARAM$kaggle$cortes) {
    tb_prediccion[, Predicted := 0L]
    tb_prediccion[1:envios, Predicted := 1L]
    
    archivo_kaggle <- sprintf("./kaggle/KA%d_%d.csv", PARAM$experimento, envios)
    
    fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
      file = archivo_kaggle,
      sep = ",")
    
    comando <- "kaggle competitions submit "
    competencia <- paste("-c", PARAM$kaggle$competencia)
    arch <- paste("-f", archivo_kaggle)
    mensaje <- sprintf("-m 'envios=%d semilla=%d'", envios, semilla_actual)
    
    linea <- paste(comando, competencia, arch, mensaje)
    salida <- system(linea, intern = TRUE)
    Sys.sleep(30)
    cat(salida, "\n")
  }
  
  # ------------------------------------------------------------------
  # 9) Guardo PARAM.yml de esta semilla
  # ------------------------------------------------------------------
  PARAM$out <- list()
  PARAM$out$lgbm$AUC <- AUC_mejor
  PARAM$out$lgbm$mejores_hiperparametros <- mejores_hp
  
  if (!require("yaml")) install.packages("yaml")
  require("yaml")
  write_yaml(PARAM, file = sprintf("PARAM_semilla_%d.yml", semilla_actual))
  
  # Limpio objetos pesados antes de la siguiente iteracion
  rm(dtrain, dvalidate, dfinal_train, final_model, tb_nueva, tb_prediccion, prediccion)
  gc(full = TRUE, verbose = FALSE)
  
  cat(sprintf("\n*** FIN SEMILLA %d  -  %s ***\n",
    semilla_actual, format(Sys.time(), "%a %b %d %X %Y")))
}

# ============================================================================
# RESUMEN FINAL
# ============================================================================

cat("\n\n")
cat("============================================================\n")
cat("  RESUMEN DE LAS 5 SEMILLAS\n")
cat("============================================================\n")
print(tb_resultado_semillas[, .(semilla, AUC_grid)])

# Guardo tabla resumen final
fwrite(tb_resultado_semillas[, .(semilla, AUC_grid)],
  file = "tb_resumen_5semillas.txt",
  sep = "\t")

cat("\n")
cat(format(Sys.time(), "Fin total: %a %b %d %X %Y\n"))

Loading required package: lightgbm

============================================================
  SEMILLA 1 de 10  -->  146023
============================================================
Tue Sep 15 01:24:56 2026

--- Grid Search para semilla 146023 ---
Inicio: Tue Sep 15 01:25:04 2026

Mejor AUC semilla 146023: 0.929753
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 119


--- Final Training para semilla 146023 ---

--- Submits a Kaggle para semilla 146023 ---
38 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
37 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
36 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
35 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
34 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
33 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
32 submissions remaining today. Successfully submitted to UTN 2026 virtual jr

Loading required package: yaml

*** FIN SEMILLA 146023  -  Tue Sep 15 01:31:02 2026 ***


============================================================
  SEMILLA 2 de 10  -->  419921
============================================================
Tue Sep 15 01:31:02 2026

--- Grid Search para semilla 419921 ---
Inicio: Tue Sep 15 01:31:05 2026

Mejor AUC semilla 419921: 0.931251
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 211


--- Final Training para semilla 419921 ---

--- Submits a Kaggle para semilla 419921 ---
31 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
30 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
29 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
28 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
27 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
26 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
25 submissions remaining today. Successfully submitted to UTN 2026 virtual jr

*** FIN SEMILLA 419921  -  Tue Sep 15 01:37:20 2026 ***


============================================================
  SEMILLA 3 de 10  -->  453601
============================================================
Tue Sep 15 01:37:20 2026

--- Grid Search para semilla 453601 ---
Inicio: Tue Sep 15 01:37:23 2026

Mejor AUC semilla 453601: 0.931435
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 139


--- Final Training para semilla 453601 ---

--- Submits a Kaggle para semilla 453601 ---
24 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
23 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
22 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
21 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
20 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
19 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
18 submissions remaining today. Successfully submitted to UTN 2026 virtual jr

*** FIN SEMILLA 453601  -  Tue Sep 15 01:43:12 2026 ***


============================================================
  SEMILLA 4 de 10  -->  906313
============================================================
Tue Sep 15 01:43:12 2026

--- Grid Search para semilla 906313 ---
Inicio: Tue Sep 15 01:43:14 2026

Mejor AUC semilla 906313: 0.930643
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 281


--- Final Training para semilla 906313 ---

--- Submits a Kaggle para semilla 906313 ---
17 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
16 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
15 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
14 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
13 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
12 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
11 submissions remaining today. Successfully submitted to UTN 2026 virtual jr

*** FIN SEMILLA 906313  -  Tue Sep 15 01:49:52 2026 ***


============================================================
  SEMILLA 5 de 10  -->  994481
============================================================
Tue Sep 15 01:49:52 2026

--- Grid Search para semilla 994481 ---
Inicio: Tue Sep 15 01:49:55 2026

Mejor AUC semilla 994481: 0.931358
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 284


--- Final Training para semilla 994481 ---

--- Submits a Kaggle para semilla 994481 ---
10 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
9 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
8 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
7 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
6 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
5 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
4 submissions remaining today. Successfully submitted to UTN 2026 virtual jr

*** FIN SEMILLA 994481  -  Tue Sep 15 01:56:35 2026 ***


============================================================
  SEMILLA 6 de 10  -->  100003
============================================================
Tue Sep 15 01:56:35 2026

--- Grid Search para semilla 100003 ---
Inicio: Tue Sep 15 01:56:37 2026

Mejor AUC semilla 100003: 0.930858
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 238


--- Final Training para semilla 100003 ---

--- Submits a Kaggle para semilla 100003 ---
3 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
2 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
1 submissions remaining today. Successfully submitted to UTN 2026 virtual jr
0 submissions remaining today. Successfully submitted to UTN 2026 virtual jr

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9306_2200.csv -m 'envios=2200 semilla=100003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9306_2300.csv -m 'envios=2300 semilla=100003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9306_2400.csv -m 'envios=2400 semilla=100003'' had status 1”

*** FIN SEMILLA 100003  -  Tue Sep 15 02:02:58 2026 ***


============================================================
  SEMILLA 7 de 10  -->  200003
============================================================
Tue Sep 15 02:02:58 2026

--- Grid Search para semilla 200003 ---
Inicio: Tue Sep 15 02:03:00 2026

Mejor AUC semilla 200003: 0.930759
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 175


--- Final Training para semilla 200003 ---

--- Submits a Kaggle para semilla 200003 ---

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_1800.csv -m 'envios=1800 semilla=200003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_1900.csv -m 'envios=1900 semilla=200003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_2000.csv -m 'envios=2000 semilla=200003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_2100.csv -m 'envios=2100 semilla=200003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_2200.csv -m 'envios=2200 semilla=200003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_2300.csv -m 'envios=2300 semilla=200003'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9307_2400.csv -m 'envios=2400 semilla=200003'' had status 1”

*** FIN SEMILLA 200003  -  Tue Sep 15 02:08:56 2026 ***


============================================================
  SEMILLA 8 de 10  -->  300007
============================================================
Tue Sep 15 02:08:56 2026

--- Grid Search para semilla 300007 ---
Inicio: Tue Sep 15 02:08:59 2026

Mejor AUC semilla 300007: 0.931020
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 164


--- Final Training para semilla 300007 ---

--- Submits a Kaggle para semilla 300007 ---

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_1800.csv -m 'envios=1800 semilla=300007'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_1900.csv -m 'envios=1900 semilla=300007'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_2000.csv -m 'envios=2000 semilla=300007'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_2100.csv -m 'envios=2100 semilla=300007'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_2200.csv -m 'envios=2200 semilla=300007'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_2300.csv -m 'envios=2300 semilla=300007'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9308_2400.csv -m 'envios=2400 semilla=300007'' had status 1”

*** FIN SEMILLA 300007  -  Tue Sep 15 02:14:51 2026 ***


============================================================
  SEMILLA 9 de 10  -->  400009
============================================================
Tue Sep 15 02:14:51 2026

--- Grid Search para semilla 400009 ---
Inicio: Tue Sep 15 02:14:54 2026

Mejor AUC semilla 400009: 0.929473
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 140


--- Final Training para semilla 400009 ---

--- Submits a Kaggle para semilla 400009 ---

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_1800.csv -m 'envios=1800 semilla=400009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_1900.csv -m 'envios=1900 semilla=400009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_2000.csv -m 'envios=2000 semilla=400009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_2100.csv -m 'envios=2100 semilla=400009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_2200.csv -m 'envios=2200 semilla=400009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_2300.csv -m 'envios=2300 semilla=400009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9309_2400.csv -m 'envios=2400 semilla=400009'' had status 1”

*** FIN SEMILLA 400009  -  Tue Sep 15 02:20:37 2026 ***


============================================================
  SEMILLA 10 de 10  -->  500009
============================================================
Tue Sep 15 02:20:37 2026

--- Grid Search para semilla 500009 ---
Inicio: Tue Sep 15 02:20:40 2026

Mejor AUC semilla 500009: 0.931871
$num_leaves
[1] 64

$min_data_in_leaf
[1] 128

$feature_fraction
[1] 0.5

$num_iterations
[1] 162


--- Final Training para semilla 500009 ---

--- Submits a Kaggle para semilla 500009 ---

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_1800.csv -m 'envios=1800 semilla=500009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_1900.csv -m 'envios=1900 semilla=500009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_2000.csv -m 'envios=2000 semilla=500009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_2100.csv -m 'envios=2100 semilla=500009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_2200.csv -m 'envios=2200 semilla=500009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_2300.csv -m 'envios=2300 semilla=500009'' had status 1”

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit  -c utn-2026-virtual-jr -f ./kaggle/KA9310_2400.csv -m 'envios=2400 semilla=500009'' had status 1”

*** FIN SEMILLA 500009  -  Tue Sep 15 02:26:36 2026 ***


============================================================
  RESUMEN DE LAS 5 SEMILLAS
============================================================
    semilla  AUC_grid
      <num>     <num>
 1:  146023 0.9297528
 2:  419921 0.9312514
 3:  453601 0.9314350
 4:  906313 0.9306433
 5:  994481 0.9313582
 6:  100003 0.9308584
 7:  200003 0.9307588
 8:  300007 0.9310199
 9:  400009 0.9294735
10:  500009 0.9318706

Fin total: Tue Sep 15 02:26:36 2026

In [35]:
# Guardar hiperparámetros ganadores para el notebook 04
PARAM$out <- list()
PARAM$out$lgbm <- list()
PARAM$out$lgbm$AUC <- tb_nueva[1, AUC]
PARAM$out$lgbm$mejores_hiperparametros <- as.list(tb_nueva[1])
PARAM$out$lgbm$mejores_hiperparametros$AUC <- NULL

dir.create("/content/buckets/b1/exp/WF8200", recursive = TRUE, showWarnings = FALSE)
saveRDS(PARAM$out, file = "/content/buckets/b1/exp/WF9903/PARAM_out_post_tuning.rds")
cat("Hiperparámetros guardados en WF8200\n")

ERROR: Error: object 'tb_nueva' not found